// <auto-generated />
using LocalParks.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LocalParks.Migrations.LocalParks
{
    [DbContext(typeof(LocalParksContext))]
    partial class LocalParksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LocalParks.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Location = "SE Portland, at the corner of Stark and Cesar E chavez Blvd",
                            Name = "Laurelhurst Park",
                            Summary = "Designed by the same man who designed Central prak in NYC, This is a beatiful addition to Portlands central Eastern side."
                        },
                        new
                        {
                            ParkId = 2,
                            Location = "NE Portland, At the corner of 33rd and Tillamook",
                            Name = "Grant Park",
                            Summary = "Nestled in next to Grant High School, this park offers a nice retreat from the city's hustle and bustle."
                        },
                        new
                        {
                            ParkId = 3,
                            Location = "SE Portland, at the corner of 20th and Belmont Ave",
                            Name = "Colonel Sumners Park",
                            Summary = "Used to have Thirsty Thursdays here until it got kinda dirty and the cops started showing up..."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
